package com.webapp.webservice.service.jaxws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated
 * source version: 2.2
 * 
 */
@WebService(name = "HelloService", targetNamespace = "http://jaxws.service.webservice.webapp.com/")
@XmlSeeAlso({ ObjectFactory.class })
public interface HelloService {

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "sayWorld", targetNamespace = "http://jaxws.service.webservice.webapp.com/", className = "com.webapp.webservice.service.jaxws.SayWorld")
	@ResponseWrapper(localName = "sayWorldResponse", targetNamespace = "http://jaxws.service.webservice.webapp.com/", className = "com.webapp.webservice.service.jaxws.SayWorldResponse")
	public String sayWorld(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param strImpl
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "sayHello")
	@WebResult(name = "sayHelloResult", targetNamespace = "")
	@RequestWrapper(localName = "sayHello", targetNamespace = "http://jaxws.service.webservice.webapp.com/", className = "com.webapp.webservice.service.jaxws.SayHello")
	@ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://jaxws.service.webservice.webapp.com/", className = "com.webapp.webservice.service.jaxws.SayHelloResponse")
	public String sayHello(
			@WebParam(name = "strImpl", targetNamespace = "") String strImpl);

}
